[package]
name = "delegator"
version = "4.0.1"
authors = ["[your_name] <[your_email]>"]
edition = "2021"
publish = false

[dependencies]
ink = { version = "4.0.1", default-features = false }
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.3", default-features = false, features = ["derive"], optional = true }

# Contracts that will be used for cross contract calls.
accumulator = { path = "accumulator", default-features = false, features = ["ink-as-dependency"] }
adder = { path = "adder", default-features = false, features = ["ink-as-dependency"] }
subber = { path = "subber", default-features = false, features = ["ink-as-dependency"] }

[dev-dependencies]
ink_e2e = { version = "4.0.1" }

[lib]
name = "delegator"
path = "lib.rs"
crate-type = ["cdylib"]
# crate-type = [
#     # Used for normal contract Wasm blobs.
#     "cdylib",
#     # Used for ABI generation.
#     "rlib",
# ]

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
    "accumulator/std",
    "adder/std",
    "subber/std",
]
ink-as-dependency = []
e2e-tests = []
